name: Backend sanity check (C#)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types: [opened, reopened, synchronize, assigned]

permissions: 
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run tests
        run: dotnet test -c Release --nologo --no-restore
      
      - name: Build
        run: |
          dotnet publish Starlight.Backend -c Debug /p:EnvironmentName=Development -r linux-x64 -o build/linux-x64
          dotnet publish Starlight.Backend -c Debug /p:EnvironmentName=Development -r linux-arm64 -o build/linux-arm64
          dotnet publish Starlight.Backend -c Debug /p:EnvironmentName=Development -r win-x64 -o build/win-x64
          
      - name: Create package
        run: |
          sudo apt-get install zip
          zip -r linux-x64.zip build/linux-x64
          zip -r win-x64.zip build/win-x64
          zip -r linux-arm64.zip build/linux-arm64
          
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: "runnable" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Rolling release of the project
          draft: false
          tag_name: "runnable"
          make_latest: true
          body: |
            # Special delivery here!
            
            Before you are fooled by "xx days ago" text in the sidebar, I just want to tell you that,
            that is not how git `reftag`s works - **the said date is their first creation date!**
            
            The commit hash is what matter. I repeat, please **LOOK AT THE COMMIT HASH** before filling a
            ticket saying "Your delivery files are outdated!" and ruin my day!
          files: |
            linux-x64.zip
            win-x64.zip
            linux-arm64.zip