name: Sanity check

on:
    workflow_dispatch:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                cache: "npm"
                node-version: "23"

            - name: Install npm packages
              run: |
                  npm install
