name: Sanity check

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  SERVER_KEY: 6e0ba13f301b7f96abb7db39da13d678012b36d1be084fb82606f2c2755fc730
  SERVER_PORT: 6969

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "23"

      - name: Install (or restore) npm packages
        run: |
          npm ci

      - name: Setup database.
        run: |
          npm run prisma --workspace server
          npm run prisma:seed --workspace server

      - name: Run test suite for backend.
        run: |
          npm run test --workspace server

      - name: Smoke build the frontend app.
        run: |
          npm run build:win --workspace frontend

      - name: Un-shit the code.
        run: |
          npm run prettify

      - name: Commit formatted code.
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci skip] Automated code format commit."
